version: "3.8"

services:
  backend:
    container_name: qr-backend
    image: node:12-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/server
    command: sh -c 'cd /server && yarn && yarn dev'
    environment:
      NODE_ENV: development